### ISSUE TITLE
fatal error: 'mysql.h' file not found

### ISSUE THREAD

**Issue by reedfoxy** [eosBLACK/eosio_mysqldb_plugin#4]
필수 라이브러리 설치를 해야 정상적으로 빌드가 됩니다. (ubuntu 기준)
sudo apt install libmysqlclient-dev
위 라이브러리가 설치되어 있지 않다면  fatal error: 'mysql.h' file not found 빌드 오류가 뜹니다.
메인화면에 위 라이브러리를 설치해야 된다는 안내 문구가 포함되었으면 합니다. 감사합니다.

**Comment by eosBLACK** [comment]
README.md 파일에 추가하도록 하겠습니다. 감사합니다.
